name: Main Api CD/CD
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  CI: false
  env_main: ${{ secrets.ENV_MAIN }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: import env file
        run: |
          touch ./.env && echo "$env_main" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: phasezero/phasezero-backend:main

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .
