version: '3.8'

services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nestjs_network

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=KOIB
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5421:5432'
    command: -p 5432
    networks:
      - nestjs_network
  redis:
    container_name: redis
    image: 'redis/redis-stack-server:latest'
    restart: always
    ports:
      - '6379:6379'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge

volumes:
  postgres:
    name: nest-db
