version: '3.8'
services:
  redis:
    image: 'redis/redis-stack-server:latest'
    restart: always
    ports:
      - '6379:6379'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge

volumes:
  postgres:
    name: nest-db
